name: Build driver
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: https://downloads.limelightvision.io/images/limelight2_2023_2.zip
        cpu: cortex-a7
        image_additional_mb: 1500
        bind_mount_repository: true
        commands: |
            mkdir /tmp/dpkg
            cd /tmp/dpkg
            wget http://security.debian.org/debian-security/pool/updates/main/d/dpkg/dpkg_1.18.26_arm64.deb
            ar x dpkg*.deb data.tar.gz
            tar xvzf data.tar.gz ./usr/bin/dpkg
            cp ./usr/bin/dpkg /usr/bin/
            apt-get update
            apt-get install --reinstall dpkg            


            wget http://security.debian.org/debian-security/pool/updates/main/a/apt/apt_1.4.11_arm64.deb -O apt.deb
            dpkg -i apt.deb
            chmod +x install.sh
            ./install.sh

    - name: Compress the image
      run: |
        mv ${{ steps.build_image.outputs.image }} limelight2-photon-test.img
        find .
        find /opt
        xz -0 -T 0 -v limelight2-photon-test.img
    - name: Upload release image
      uses: actions/upload-artifact@v2
      with:
        name: Image
        path: limelight2-photon-test.img
